Sil\Bundle\SonataSyliusUserBundle\Entity\SonataUser:
    type: mappedSuperclass
    table: sil_user
    fields:
        firstName:
            type: string
            length: 255
            nullable: true
        lastName:
            type: string
            length: 255
            nullable: true
        localeCode:
            type: string
            length: 12

    manyToMany:
        groups:
            inversedBy: users
            targetEntity: Sil\Bundle\SonataSyliusUserBundle\Entity\SonataGroupInterface
            joinTable:
                name: sil_user__group
                joinColumns:
                    user_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    group_id:
                        referencedColumnName: id
