Sil\Bundle\SonataSyliusUserBundle\Entity\SonataGroup:
    type:  mappedSuperclass
    table: sil_user_group
    fields:
        name:
            type: string
            nullable: false
        roles:
            type: array

    manyToMany:
        users:
            mappedBy: groups
            targetEntity: Sil\Bundle\SonataSyliusUserBundle\Entity\SonataUserInterface
