default: # see available parameters with command : app/console debug:container --parameters | grep sonata.admin
    sonata.admin.configuration.templates:
        default:
            user_block: BlastCoreBundle:Block:user_block.html.twig
        replace:
            user_block: SilSonataSyliusUserBundle:Admin/Block:user_block.html.twig
