parameters:
    blast:
        Sil\Bundle\SonataSyliusUserBundle\Entity\SonataUserInterface:
            Sonata\AdminBundle\Datagrid\ListMapper:
                add:
                    username: ~
                    email: ~
                    firstName: ~
                    lastName: ~
                    lastLogin: ~
                    locked: ~
                    expiresAt: ~
                    roles:
                        type: array
                        template: BlastCoreBundle:CRUD:list_array_roles.html.twig
                    _options:
                        fieldsOrder:
                            - username
                            - email
                            - firstName
                            - lastName
                            - lastLogin
                            - locked
                            - expiresAt
                            - roles
            Sonata\AdminBundle\Datagrid\DatagridMapper:
                add:
                    username: ~
                    email: ~
                    firstName: ~
                    lastName: ~
                    lastLogin: ~
                    locked: ~
                    expiresAt: ~
                    roles: ~
                    _options:
                        fieldsOrder:
                            - username
                            - email
                            - firstName
                            - lastName
                            - lastLogin
                            - locked
                            - expiresAt
                            - roles
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    form_tab_general:
                        form_group_general:
                            username: ~
                            firstName: ~
                            lastName: ~
                            email: ~
                        form_group_details:
                            enabled:
                                type: checkbox
                                required: false
                            locked:
                                type: checkbox
                                required: false
                            expired:
                                type: checkbox
                                required: false
                            expiresAt:
                                type: sonata_type_date_picker
                                required: false
                        form_group_password:
                            plainPassword:
                                type: repeated
                                required: false
                                first_options:
                                    label: sil.sonatasyliususerbundle.first_password
                                second_options:
                                    label: sil.sonatasyliususerbundle.second_password
                        form_group_roles:
                            roles: ~
            Sonata\AdminBundle\Show\ShowMapper:
                add:
                    form_tab_general:
                        form_group_general:
                            username: ~
                            firstName: ~
                            lastName: ~
                            email: ~
                        form_group_details:
                            enabled: ~
                            locked: ~
                            expired:
                                type: checkbox
                            expiresAt:
                                type: sonata_type_date_picker
                        form_group_roles:
                            roles:
                                type: array
                                template: BlastCoreBundle:CRUD:show_array_roles.html.twig

        Sil\Bundle\SonataSyliusUserBundle\Entity\SonataGroupInterface:
            Sonata\AdminBundle\Datagrid\ListMapper:
                add:
                    name: ~
                    roles: ~
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    name: ~
                    roles: ~
            Sonata\AdminBundle\Show\ShowMapper:
                _copy: Sonata\AdminBundle\Form\FormMapper

        Sil\Bundle\SonataSyliusUserBundle\Entity\Traits\Traceable:
            Sonata\AdminBundle\Show\ShowMapper:
                add:
                    form_tab_history:
                        form_group_history:
                            createdBy: ~
                            updatedBy: ~
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    form_tab_history:
                        form_group_history:
                            createdBy:
                                type: entity
                                class: Sil\Bundle\SonataSyliusUserBundle\Entity\SonataUser
                                disabled: true
                                required: false
                            updatedBy:
                                type: entity
                                class: Sil\Bundle\SonataSyliusUserBundle\Entity\SonataUser
                                disabled: true
                                required: false

        Sil\Bundle\SonataSyliusUserBundle\Entity\Traits\Ownable:
            Sonata\AdminBundle\Datagrid\DatagridMapper:
                add:
                    owner: ~
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    form_group_specifics:
                        form_group_misc:
                            owner:
                                type: entity
                                class: Sil\Bundle\SonataSyliusUserBundle\Entity\SonataUser
                                required: false
