services:

    sil_sonata_sylius_user.admin.sonata_user:
        class: Sil\Bundle\SonataSyliusUserBundle\Admin\SonataUserAdmin
        arguments: [~, "%sil_sonata_sylius_user.entity.sonata_user.class%", BlastCoreBundle:CRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: sil.sonata_sylius_user.menu_label.sonata_user
              label_translator_strategy: blast.resource.sonata.label_strategy.prefix
